### ISSUE TITLE
Support /oauth/token endpoint

### ISSUE THREAD

**Issue by jonahkagan** [Clever/clever-js#12]
The library should wrap the /oauth/token endpoint doc'd here: https://getclever.com/developers/docs/oauth/reference. There should also be a mock for this endpoint so library users can test their implementation of the Clever OAuth flow.

**Comment by jloveridge** [comment]
I have implemented the OAuth endpoints in [my fork](https://github.com/gradecam/clever-js) of the repository. I am hoping it will be merged soon.
