### ISSUE TITLE
Support for student contacts

### ISSUE THREAD

**Issue by srivatsansangha** [Clever/clever-js#50]
Hi,
   There does not seem to be a way to pull student contact info using this library (v1.1/students/{id}/contacts end point). 

Thanks
Sri

**Comment by tyleralves** [comment]
Does clever accept PRs from non-organization contributors? I'd take this one, but it appears that outside PRs aren't welcome(?) I'm not trying to criticize, I just want to know that my contribution will be considered and your PR history is a bit concerning.

Cheers,
Tyler

**Comment by tyleralves** [comment]
Appears that this library provides access to the top level endpoints only (ie: /students, /teachers, /districts, etc). 

For now you could call the api directly within an express app (server-side) using the following:
```
var express = require('express');
var router = express.Router();
var clever = require('clever')({token: 'DEMO_TOKEN'});
var quest = require('quest');

/* GET home page. */
router.get('/', function(req, res, next) {
  // Replace with id for which you would like to retrieve contacts  
  var studentId = '530e5960049e75a9262cff1d'; 
  // Setup quest options
  var options = {
    uri: "https://api.clever.com/v1.1/students/" + studentId + "/contacts",
    method: "GET",
    headers: {Authorization: "Bearer DEMO_TOKEN"}
  };
  // Make api call
  quest(options, function(err, response, contacts){
    console.log(contacts);
    res.render('index', { title: 'Express', contacts: contacts});
  });
});

module.exports = router;
```

Note: You can also do this client-side if you'd like, but you'd have to compile the quest package and include it in your view.

Hope this helps! 
Tyler
